CREATE TABLE IF NOT EXISTS reservations (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    reserver_ID INTEGER NOT NULL,
    editionID INTEGER NOT NULL,
    datePlaced DATE NOT NULL,

    FOREIGN KEY (reserver_ID) REFERENCES readers(ID),
    FOREIGN KEY (editionID) REFERENCES editions(ID)
);